services:
  web:
    image: bloxtor_demo_web
    ports:
      - "8890:80"   # (optional, but not needed if you want 8888 only)
    #volumes:
    #  - .:/var/www/html
    command: >
      /bin/bash -c "
        /bin/sed -i \"s/my_first_db/${DOCKER_COMPOSE_DB_NAME}/g\" /var/www/html/app/config/global_variables.php
        /bin/sed -i \"s/phpframeworkdemo/${DOCKER_COMPOSE_DB_USER}/g\" /var/www/html/app/config/global_variables.php
        /bin/sed -i \"s/d4d7r@w3m0rkp3w0/${DOCKER_COMPOSE_DB_PASS}/g\" /var/www/html/app/config/global_variables.php
        
        # Add correct mysql host
        /bin/sed -i \"s/127.0.0.1/mysql/g\" /var/www/html/app/config/bean/mysql_dbdriver.xml
        /bin/sed -i \"s/127.0.0.1/mysql/g\" /var/www/html/other/workflow/layer/layers.xml
        /bin/sed -i \"s/127.0.0.1/mysql/g\" /var/www/html/other/workflow/layer/layers_simple.xml
      "
    depends_on:
      - mysql
  mysql:
    image: bloxtor_demo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_COMPOSE_DB_ROOT_PASS}
      MYSQL_DATABASE: ${DOCKER_COMPOSE_DB_NAME}
      MYSQL_USER: ${DOCKER_COMPOSE_DB_USER}
      MYSQL_PASSWORD: ${DOCKER_COMPOSE_DB_PASS}
    ports:
      - "8891:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf
