<?php
trait PostgresDBProperty {
	private static $default_schema = "public";
	
	private static $default_odbc_data_source = null; //To be set by the developer, so it can be used in all drivers
	private static $default_odbc_driver = null; //To be set by the developer, so it can be used in all drivers
	
	private static $available_php_extension_types = array(); //will be init on construct
	
	private static $ignore_connection_options = array(); //will be used in the layers diagram, set DB settings and others
	private static $ignore_connection_options_by_extension = array(
		"pg" => array("odbc_data_source", "odbc_driver", "extra_dsn", "extra_settings"),
		"odbc" => array("extra_settings")
	); //will be used in the layers diagram, set DB settings and others
	
	//More info in https://www.postgresql.org/docs/9.5/multibyte.html.
	private static $db_connection_encodings = array( //used to connect to a DB or to create a DB
		"utf8" => "Unicode, 8-bit", 
		"latin1" => "ISO 8859-1, ECMA 94", 
		"latin2" => "ISO 8859-2, ECMA 94", 
		"latin3" => "ISO 8859-3, ECMA 94", 
		"latin4" => "ISO 8859-4, ECMA 94", 
		"latin5" => "ISO 8859-9, ECMA 128", 
		"latin6" => "ISO 8859-10, ECMA 144", 
		"latin7" => "ISO 8859-13", 
		"latin8" => "ISO 8859-14", 
		"latin9" => "ISO 8859-15", 
		"latin10" => "ISO 8859-16, ASRO SR 14111", 
		"big5" => "Big Five", 
		"euc_cn" => "Extended UNIX Code-CN", 
		"euc_jp" => "Extended UNIX Code-JP", 
		"euc_jis_2004" => "Extended UNIX Code-JP, JIS X 0213", 
		"euc_kr" => "Extended UNIX Code-KR", 
		"euc_tw" => "Extended UNIX Code-TW", 
		"gb18030" => "National Standard", 
		"gbk" => "Extended National Standard", 
		"iso_8859_5" => "ISO 8859-5, ECMA 113", 
		"iso_8859_6" => "ISO 8859-6, ECMA 114", 
		"iso_8859_7" => "ISO 8859-7, ECMA 118", 
		"iso_8859_8" => "ISO 8859-8, ECMA 121", 
		"johab" => "JOHAB", 
		"koi8r" => "KOI8-R", 
		"koi8u" => "KOI8-U", 
		"mule_internal" => "Mule internal code", 
		"sjis" => "Shift JIS", 
		"shift_jis_2004" => "Shift JIS, JIS X 0213", 
		"sql_ascii" => "unspecified (see text)", 
		"uhc" => "Unified Hangul Code", 
		"win866" => "Windows CP866", 
		"win874" => "Windows CP874", 
		"win1250" => "Windows CP1250", 
		"win1251" => "Windows CP1251", 
		"win1252" => "Windows CP1252", 
		"win1253" => "Windows CP1253", 
		"win1254" => "Windows CP1254", 
		"win1255" => "Windows CP1255", 
		"win1256" => "Windows CP1256", 
		"win1257" => "Windows CP1257", 
		"win1258" => "Windows CP1258", 
	);
	
	//To get more collations please query the sql: SELECT * FROM pg_collation;
	private static $column_collations = array( //used to create column
		"C" => "C", 
		"POSIX" => "POSIX", 
		"ucs_basic" => "ucs_basic", 
		"C.UTF-8" => "C.UTF-8", 
		"en_AG" => "en_AG", 
		"en_AG.utf8" => "en_AG.utf8", 
		"en_AU.utf8" => "en_AU.utf8", 
		"en_BW.utf8" => "en_BW.utf8", 
		"en_CA.utf8" => "en_CA.utf8", 
		"en_DK.utf8" => "en_DK.utf8", 
		"en_GB.utf8" => "en_GB.utf8", 
		"en_HK.utf8" => "en_HK.utf8", 
		"en_IE.utf8" => "en_IE.utf8", 
		"en_IL" => "en_IL", 
		"en_IL.utf8" => "en_IL.utf8", 
		"en_IN" => "en_IN", 
		"en_IN.utf8" => "en_IN.utf8", 
		"en_NG" => "en_NG", 
		"en_NG.utf8" => "en_NG.utf8", 
		"en_NZ.utf8" => "en_NZ.utf8", 
		"en_PH.utf8" => "en_PH.utf8", 
		"en_SG.utf8" => "en_SG.utf8", 
		"en_US.utf8" => "en_US.utf8", 
		"en_ZA.utf8" => "en_ZA.utf8", 
		"en_ZM" => "en_ZM", 
		"en_ZM.utf8" => "en_ZM.utf8", 
		"en_ZW.utf8" => "en_ZW.utf8", 
		"pt_PT.utf8" => "pt_PT.utf8", 
		"en_AU" => "en_AU", 
		"en_BW" => "en_BW", 
		"en_CA" => "en_CA", 
		"en_DK" => "en_DK", 
		"en_GB" => "en_GB", 
		"en_HK" => "en_HK", 
		"en_IE" => "en_IE", 
		"en_NZ" => "en_NZ", 
		"en_PH" => "en_PH", 
		"en_SG" => "en_SG", 
		"en_US" => "en_US", 
		"en_ZA" => "en_ZA", 
		"en_ZW" => "en_ZW", 
		"pt_PT" => "pt_PT", 
		"und-x-icu" => "und-x-icu", 
		"af-x-icu" => "af-x-icu", 
		"af-NA-x-icu" => "af-NA-x-icu", 
		"af-ZA-x-icu" => "af-ZA-x-icu", 
		"agq-x-icu" => "agq-x-icu", 
		"agq-CM-x-icu" => "agq-CM-x-icu", 
		"ak-x-icu" => "ak-x-icu", 
		"ak-GH-x-icu" => "ak-GH-x-icu", 
		"am-x-icu" => "am-x-icu", 
		"am-ET-x-icu" => "am-ET-x-icu", 
		"ar-x-icu" => "ar-x-icu", 
		"ar-001-x-icu" => "ar-001-x-icu", 
		"ar-AE-x-icu" => "ar-AE-x-icu", 
		"ar-BH-x-icu" => "ar-BH-x-icu", 
		"ar-DJ-x-icu" => "ar-DJ-x-icu", 
		"ar-DZ-x-icu" => "ar-DZ-x-icu", 
		"ar-EG-x-icu" => "ar-EG-x-icu", 
		"ar-EH-x-icu" => "ar-EH-x-icu", 
		"ar-ER-x-icu" => "ar-ER-x-icu", 
		"ar-IL-x-icu" => "ar-IL-x-icu", 
		"ar-IQ-x-icu" => "ar-IQ-x-icu", 
		"ar-JO-x-icu" => "ar-JO-x-icu", 
		"ar-KM-x-icu" => "ar-KM-x-icu", 
		"ar-KW-x-icu" => "ar-KW-x-icu", 
		"ar-LB-x-icu" => "ar-LB-x-icu", 
		"ar-LY-x-icu" => "ar-LY-x-icu", 
		"ar-MA-x-icu" => "ar-MA-x-icu", 
		"ar-MR-x-icu" => "ar-MR-x-icu", 
		"ar-OM-x-icu" => "ar-OM-x-icu", 
		"ar-PS-x-icu" => "ar-PS-x-icu", 
		"ar-QA-x-icu" => "ar-QA-x-icu", 
		"ar-SA-x-icu" => "ar-SA-x-icu", 
		"ar-SD-x-icu" => "ar-SD-x-icu", 
		"ar-SO-x-icu" => "ar-SO-x-icu", 
		"ar-SS-x-icu" => "ar-SS-x-icu", 
		"ar-SY-x-icu" => "ar-SY-x-icu", 
		"ar-TD-x-icu" => "ar-TD-x-icu", 
		"ar-TN-x-icu" => "ar-TN-x-icu", 
		"ar-YE-x-icu" => "ar-YE-x-icu", 
		"as-x-icu" => "as-x-icu", 
		"as-IN-x-icu" => "as-IN-x-icu", 
		"asa-x-icu" => "asa-x-icu", 
		"asa-TZ-x-icu" => "asa-TZ-x-icu", 
		"ast-x-icu" => "ast-x-icu", 
		"ast-ES-x-icu" => "ast-ES-x-icu", 
		"az-x-icu" => "az-x-icu", 
		"az-Cyrl-x-icu" => "az-Cyrl-x-icu", 
		"az-Cyrl-AZ-x-icu" => "az-Cyrl-AZ-x-icu", 
		"az-Latn-x-icu" => "az-Latn-x-icu", 
		"az-Latn-AZ-x-icu" => "az-Latn-AZ-x-icu", 
		"bas-x-icu" => "bas-x-icu", 
		"bas-CM-x-icu" => "bas-CM-x-icu", 
		"be-x-icu" => "be-x-icu", 
		"be-BY-x-icu" => "be-BY-x-icu", 
		"bem-x-icu" => "bem-x-icu", 
		"bem-ZM-x-icu" => "bem-ZM-x-icu", 
		"bez-x-icu" => "bez-x-icu", 
		"bez-TZ-x-icu" => "bez-TZ-x-icu", 
		"bg-x-icu" => "bg-x-icu", 
		"bg-BG-x-icu" => "bg-BG-x-icu", 
		"bm-x-icu" => "bm-x-icu", 
		"bm-ML-x-icu" => "bm-ML-x-icu", 
		"bn-x-icu" => "bn-x-icu", 
		"bn-BD-x-icu" => "bn-BD-x-icu", 
		"bn-IN-x-icu" => "bn-IN-x-icu", 
		"bo-x-icu" => "bo-x-icu", 
		"bo-CN-x-icu" => "bo-CN-x-icu", 
		"bo-IN-x-icu" => "bo-IN-x-icu", 
		"br-x-icu" => "br-x-icu", 
		"br-FR-x-icu" => "br-FR-x-icu", 
		"brx-x-icu" => "brx-x-icu", 
		"brx-IN-x-icu" => "brx-IN-x-icu", 
		"bs-x-icu" => "bs-x-icu", 
		"bs-Cyrl-x-icu" => "bs-Cyrl-x-icu", 
		"bs-Cyrl-BA-x-icu" => "bs-Cyrl-BA-x-icu", 
		"bs-Latn-x-icu" => "bs-Latn-x-icu", 
		"bs-Latn-BA-x-icu" => "bs-Latn-BA-x-icu", 
		"ca-x-icu" => "ca-x-icu", 
		"ca-AD-x-icu" => "ca-AD-x-icu", 
		"ca-ES-x-icu" => "ca-ES-x-icu", 
		"ca-FR-x-icu" => "ca-FR-x-icu", 
		"ca-IT-x-icu" => "ca-IT-x-icu", 
		"ccp-x-icu" => "ccp-x-icu", 
		"ccp-BD-x-icu" => "ccp-BD-x-icu", 
		"ccp-IN-x-icu" => "ccp-IN-x-icu", 
		"ce-x-icu" => "ce-x-icu", 
		"ce-RU-x-icu" => "ce-RU-x-icu", 
		"cgg-x-icu" => "cgg-x-icu", 
		"cgg-UG-x-icu" => "cgg-UG-x-icu", 
		"chr-x-icu" => "chr-x-icu", 
		"chr-US-x-icu" => "chr-US-x-icu", 
		"ckb-x-icu" => "ckb-x-icu", 
		"ckb-IQ-x-icu" => "ckb-IQ-x-icu", 
		"ckb-IR-x-icu" => "ckb-IR-x-icu", 
		"cs-x-icu" => "cs-x-icu", 
		"cs-CZ-x-icu" => "cs-CZ-x-icu", 
		"cy-x-icu" => "cy-x-icu", 
		"cy-GB-x-icu" => "cy-GB-x-icu", 
		"da-x-icu" => "da-x-icu", 
		"da-DK-x-icu" => "da-DK-x-icu", 
		"da-GL-x-icu" => "da-GL-x-icu", 
		"dav-x-icu" => "dav-x-icu", 
		"dav-KE-x-icu" => "dav-KE-x-icu", 
		"de-x-icu" => "de-x-icu", 
		"de-AT-x-icu" => "de-AT-x-icu", 
		"de-BE-x-icu" => "de-BE-x-icu", 
		"de-CH-x-icu" => "de-CH-x-icu", 
		"de-DE-x-icu" => "de-DE-x-icu", 
		"de-IT-x-icu" => "de-IT-x-icu", 
		"de-LI-x-icu" => "de-LI-x-icu", 
		"de-LU-x-icu" => "de-LU-x-icu", 
		"dje-x-icu" => "dje-x-icu", 
		"dje-NE-x-icu" => "dje-NE-x-icu", 
		"dsb-x-icu" => "dsb-x-icu", 
		"dsb-DE-x-icu" => "dsb-DE-x-icu", 
		"dua-x-icu" => "dua-x-icu", 
		"dua-CM-x-icu" => "dua-CM-x-icu", 
		"dyo-x-icu" => "dyo-x-icu", 
		"dyo-SN-x-icu" => "dyo-SN-x-icu", 
		"dz-x-icu" => "dz-x-icu", 
		"dz-BT-x-icu" => "dz-BT-x-icu", 
		"ebu-x-icu" => "ebu-x-icu", 
		"ebu-KE-x-icu" => "ebu-KE-x-icu", 
		"ee-x-icu" => "ee-x-icu", 
		"ee-GH-x-icu" => "ee-GH-x-icu", 
		"ee-TG-x-icu" => "ee-TG-x-icu", 
		"el-x-icu" => "el-x-icu", 
		"el-CY-x-icu" => "el-CY-x-icu", 
		"el-GR-x-icu" => "el-GR-x-icu", 
		"en-x-icu" => "en-x-icu", 
		"en-001-x-icu" => "en-001-x-icu", 
		"en-150-x-icu" => "en-150-x-icu", 
		"en-AG-x-icu" => "en-AG-x-icu", 
		"en-AI-x-icu" => "en-AI-x-icu", 
		"en-AS-x-icu" => "en-AS-x-icu", 
		"en-AT-x-icu" => "en-AT-x-icu", 
		"en-AU-x-icu" => "en-AU-x-icu", 
		"en-BB-x-icu" => "en-BB-x-icu", 
		"en-BE-x-icu" => "en-BE-x-icu", 
		"en-BI-x-icu" => "en-BI-x-icu", 
		"en-BM-x-icu" => "en-BM-x-icu", 
		"en-BS-x-icu" => "en-BS-x-icu", 
		"en-BW-x-icu" => "en-BW-x-icu", 
		"en-BZ-x-icu" => "en-BZ-x-icu", 
		"en-CA-x-icu" => "en-CA-x-icu", 
		"en-CC-x-icu" => "en-CC-x-icu", 
		"en-CH-x-icu" => "en-CH-x-icu", 
		"en-CK-x-icu" => "en-CK-x-icu", 
		"en-CM-x-icu" => "en-CM-x-icu", 
		"en-CX-x-icu" => "en-CX-x-icu", 
		"en-CY-x-icu" => "en-CY-x-icu", 
		"en-DE-x-icu" => "en-DE-x-icu", 
		"en-DG-x-icu" => "en-DG-x-icu", 
		"en-DK-x-icu" => "en-DK-x-icu", 
		"en-DM-x-icu" => "en-DM-x-icu", 
		"en-ER-x-icu" => "en-ER-x-icu", 
		"en-FI-x-icu" => "en-FI-x-icu", 
		"en-FJ-x-icu" => "en-FJ-x-icu", 
		"en-FK-x-icu" => "en-FK-x-icu", 
		"en-FM-x-icu" => "en-FM-x-icu", 
		"en-GB-x-icu" => "en-GB-x-icu", 
		"en-GD-x-icu" => "en-GD-x-icu", 
		"en-GG-x-icu" => "en-GG-x-icu", 
		"en-GH-x-icu" => "en-GH-x-icu", 
		"en-GI-x-icu" => "en-GI-x-icu", 
		"en-GM-x-icu" => "en-GM-x-icu", 
		"en-GU-x-icu" => "en-GU-x-icu", 
		"en-GY-x-icu" => "en-GY-x-icu", 
		"en-HK-x-icu" => "en-HK-x-icu", 
		"en-IE-x-icu" => "en-IE-x-icu", 
		"en-IL-x-icu" => "en-IL-x-icu", 
		"en-IM-x-icu" => "en-IM-x-icu", 
		"en-IN-x-icu" => "en-IN-x-icu", 
		"en-IO-x-icu" => "en-IO-x-icu", 
		"en-JE-x-icu" => "en-JE-x-icu", 
		"en-JM-x-icu" => "en-JM-x-icu", 
		"en-KE-x-icu" => "en-KE-x-icu", 
		"en-KI-x-icu" => "en-KI-x-icu", 
		"en-KN-x-icu" => "en-KN-x-icu", 
		"en-KY-x-icu" => "en-KY-x-icu", 
		"en-LC-x-icu" => "en-LC-x-icu", 
		"en-LR-x-icu" => "en-LR-x-icu", 
		"en-LS-x-icu" => "en-LS-x-icu", 
		"en-MG-x-icu" => "en-MG-x-icu", 
		"en-MH-x-icu" => "en-MH-x-icu", 
		"en-MO-x-icu" => "en-MO-x-icu", 
		"en-MP-x-icu" => "en-MP-x-icu", 
		"en-MS-x-icu" => "en-MS-x-icu", 
		"en-MT-x-icu" => "en-MT-x-icu", 
		"en-MU-x-icu" => "en-MU-x-icu", 
		"en-MW-x-icu" => "en-MW-x-icu", 
		"en-MY-x-icu" => "en-MY-x-icu", 
		"en-NA-x-icu" => "en-NA-x-icu", 
		"en-NF-x-icu" => "en-NF-x-icu", 
		"en-NG-x-icu" => "en-NG-x-icu", 
		"en-NL-x-icu" => "en-NL-x-icu", 
		"en-NR-x-icu" => "en-NR-x-icu", 
		"en-NU-x-icu" => "en-NU-x-icu", 
		"en-NZ-x-icu" => "en-NZ-x-icu", 
		"en-PG-x-icu" => "en-PG-x-icu", 
		"en-PH-x-icu" => "en-PH-x-icu", 
		"en-PK-x-icu" => "en-PK-x-icu", 
		"en-PN-x-icu" => "en-PN-x-icu", 
		"en-PR-x-icu" => "en-PR-x-icu", 
		"en-PW-x-icu" => "en-PW-x-icu", 
		"en-RW-x-icu" => "en-RW-x-icu", 
		"en-SB-x-icu" => "en-SB-x-icu", 
		"en-SC-x-icu" => "en-SC-x-icu", 
		"en-SD-x-icu" => "en-SD-x-icu", 
		"en-SE-x-icu" => "en-SE-x-icu", 
		"en-SG-x-icu" => "en-SG-x-icu", 
		"en-SH-x-icu" => "en-SH-x-icu", 
		"en-SI-x-icu" => "en-SI-x-icu", 
		"en-SL-x-icu" => "en-SL-x-icu", 
		"en-SS-x-icu" => "en-SS-x-icu", 
		"en-SX-x-icu" => "en-SX-x-icu", 
		"en-SZ-x-icu" => "en-SZ-x-icu", 
		"en-TC-x-icu" => "en-TC-x-icu", 
		"en-TK-x-icu" => "en-TK-x-icu", 
		"en-TO-x-icu" => "en-TO-x-icu", 
		"en-TT-x-icu" => "en-TT-x-icu", 
		"en-TV-x-icu" => "en-TV-x-icu", 
		"en-TZ-x-icu" => "en-TZ-x-icu", 
		"en-UG-x-icu" => "en-UG-x-icu", 
		"en-UM-x-icu" => "en-UM-x-icu", 
		"en-US-x-icu" => "en-US-x-icu", 
		"en-US-u-va-posix-x-icu" => "en-US-u-va-posix-x-icu", 
		"en-VC-x-icu" => "en-VC-x-icu", 
		"en-VG-x-icu" => "en-VG-x-icu", 
		"en-VI-x-icu" => "en-VI-x-icu", 
		"en-VU-x-icu" => "en-VU-x-icu", 
		"en-WS-x-icu" => "en-WS-x-icu", 
		"en-ZA-x-icu" => "en-ZA-x-icu", 
		"en-ZM-x-icu" => "en-ZM-x-icu", 
		"en-ZW-x-icu" => "en-ZW-x-icu", 
		"eo-x-icu" => "eo-x-icu", 
		"es-x-icu" => "es-x-icu", 
		"es-419-x-icu" => "es-419-x-icu", 
		"es-AR-x-icu" => "es-AR-x-icu", 
		"es-BO-x-icu" => "es-BO-x-icu", 
		"es-BR-x-icu" => "es-BR-x-icu", 
		"es-BZ-x-icu" => "es-BZ-x-icu", 
		"es-CL-x-icu" => "es-CL-x-icu", 
		"es-CO-x-icu" => "es-CO-x-icu", 
		"es-CR-x-icu" => "es-CR-x-icu", 
		"es-CU-x-icu" => "es-CU-x-icu", 
		"es-DO-x-icu" => "es-DO-x-icu", 
		"es-EA-x-icu" => "es-EA-x-icu", 
		"es-EC-x-icu" => "es-EC-x-icu", 
		"es-ES-x-icu" => "es-ES-x-icu", 
		"es-GQ-x-icu" => "es-GQ-x-icu", 
		"es-GT-x-icu" => "es-GT-x-icu", 
		"es-HN-x-icu" => "es-HN-x-icu", 
		"es-IC-x-icu" => "es-IC-x-icu", 
		"es-MX-x-icu" => "es-MX-x-icu", 
		"es-NI-x-icu" => "es-NI-x-icu", 
		"es-PA-x-icu" => "es-PA-x-icu", 
		"es-PE-x-icu" => "es-PE-x-icu", 
		"es-PH-x-icu" => "es-PH-x-icu", 
		"es-PR-x-icu" => "es-PR-x-icu", 
		"es-PY-x-icu" => "es-PY-x-icu", 
		"es-SV-x-icu" => "es-SV-x-icu", 
		"es-US-x-icu" => "es-US-x-icu", 
		"es-UY-x-icu" => "es-UY-x-icu", 
		"es-VE-x-icu" => "es-VE-x-icu", 
		"et-x-icu" => "et-x-icu", 
		"et-EE-x-icu" => "et-EE-x-icu", 
		"eu-x-icu" => "eu-x-icu", 
		"eu-ES-x-icu" => "eu-ES-x-icu", 
		"ewo-x-icu" => "ewo-x-icu", 
		"ewo-CM-x-icu" => "ewo-CM-x-icu", 
		"fa-x-icu" => "fa-x-icu", 
		"fa-AF-x-icu" => "fa-AF-x-icu", 
		"fa-IR-x-icu" => "fa-IR-x-icu", 
		"ff-x-icu" => "ff-x-icu", 
		"ff-CM-x-icu" => "ff-CM-x-icu", 
		"ff-GN-x-icu" => "ff-GN-x-icu", 
		"ff-MR-x-icu" => "ff-MR-x-icu", 
		"ff-SN-x-icu" => "ff-SN-x-icu", 
		"fi-x-icu" => "fi-x-icu", 
		"fi-FI-x-icu" => "fi-FI-x-icu", 
		"fil-x-icu" => "fil-x-icu", 
		"fil-PH-x-icu" => "fil-PH-x-icu", 
		"fo-x-icu" => "fo-x-icu", 
		"fo-DK-x-icu" => "fo-DK-x-icu", 
		"fo-FO-x-icu" => "fo-FO-x-icu", 
		"fr-x-icu" => "fr-x-icu", 
		"fr-BE-x-icu" => "fr-BE-x-icu", 
		"fr-BF-x-icu" => "fr-BF-x-icu", 
		"fr-BI-x-icu" => "fr-BI-x-icu", 
		"fr-BJ-x-icu" => "fr-BJ-x-icu", 
		"fr-BL-x-icu" => "fr-BL-x-icu", 
		"fr-CA-x-icu" => "fr-CA-x-icu", 
		"fr-CD-x-icu" => "fr-CD-x-icu", 
		"fr-CF-x-icu" => "fr-CF-x-icu", 
		"fr-CG-x-icu" => "fr-CG-x-icu", 
		"fr-CH-x-icu" => "fr-CH-x-icu", 
		"fr-CI-x-icu" => "fr-CI-x-icu", 
		"fr-CM-x-icu" => "fr-CM-x-icu", 
		"fr-DJ-x-icu" => "fr-DJ-x-icu", 
		"fr-DZ-x-icu" => "fr-DZ-x-icu", 
		"fr-FR-x-icu" => "fr-FR-x-icu", 
		"fr-GA-x-icu" => "fr-GA-x-icu", 
		"fr-GF-x-icu" => "fr-GF-x-icu", 
		"fr-GN-x-icu" => "fr-GN-x-icu", 
		"fr-GP-x-icu" => "fr-GP-x-icu", 
		"fr-GQ-x-icu" => "fr-GQ-x-icu", 
		"fr-HT-x-icu" => "fr-HT-x-icu", 
		"fr-KM-x-icu" => "fr-KM-x-icu", 
		"fr-LU-x-icu" => "fr-LU-x-icu", 
		"fr-MA-x-icu" => "fr-MA-x-icu", 
		"fr-MC-x-icu" => "fr-MC-x-icu", 
		"fr-MF-x-icu" => "fr-MF-x-icu", 
		"fr-MG-x-icu" => "fr-MG-x-icu", 
		"fr-ML-x-icu" => "fr-ML-x-icu", 
		"fr-MQ-x-icu" => "fr-MQ-x-icu", 
		"fr-MR-x-icu" => "fr-MR-x-icu", 
		"fr-MU-x-icu" => "fr-MU-x-icu", 
		"fr-NC-x-icu" => "fr-NC-x-icu", 
		"fr-NE-x-icu" => "fr-NE-x-icu", 
		"fr-PF-x-icu" => "fr-PF-x-icu", 
		"fr-PM-x-icu" => "fr-PM-x-icu", 
		"fr-RE-x-icu" => "fr-RE-x-icu", 
		"fr-RW-x-icu" => "fr-RW-x-icu", 
		"fr-SC-x-icu" => "fr-SC-x-icu", 
		"fr-SN-x-icu" => "fr-SN-x-icu", 
		"fr-SY-x-icu" => "fr-SY-x-icu", 
		"fr-TD-x-icu" => "fr-TD-x-icu", 
		"fr-TG-x-icu" => "fr-TG-x-icu", 
		"fr-TN-x-icu" => "fr-TN-x-icu", 
		"fr-VU-x-icu" => "fr-VU-x-icu", 
		"fr-WF-x-icu" => "fr-WF-x-icu", 
		"fr-YT-x-icu" => "fr-YT-x-icu", 
		"fur-x-icu" => "fur-x-icu", 
		"fur-IT-x-icu" => "fur-IT-x-icu", 
		"fy-x-icu" => "fy-x-icu", 
		"fy-NL-x-icu" => "fy-NL-x-icu", 
		"ga-x-icu" => "ga-x-icu", 
		"ga-IE-x-icu" => "ga-IE-x-icu", 
		"gd-x-icu" => "gd-x-icu", 
		"gd-GB-x-icu" => "gd-GB-x-icu", 
		"gl-x-icu" => "gl-x-icu", 
		"gl-ES-x-icu" => "gl-ES-x-icu", 
		"gsw-x-icu" => "gsw-x-icu", 
		"gsw-CH-x-icu" => "gsw-CH-x-icu", 
		"gsw-FR-x-icu" => "gsw-FR-x-icu", 
		"gsw-LI-x-icu" => "gsw-LI-x-icu", 
		"gu-x-icu" => "gu-x-icu", 
		"gu-IN-x-icu" => "gu-IN-x-icu", 
		"guz-x-icu" => "guz-x-icu", 
		"guz-KE-x-icu" => "guz-KE-x-icu", 
		"gv-x-icu" => "gv-x-icu", 
		"gv-IM-x-icu" => "gv-IM-x-icu", 
		"ha-x-icu" => "ha-x-icu", 
		"ha-GH-x-icu" => "ha-GH-x-icu", 
		"ha-NE-x-icu" => "ha-NE-x-icu", 
		"ha-NG-x-icu" => "ha-NG-x-icu", 
		"haw-x-icu" => "haw-x-icu", 
		"haw-US-x-icu" => "haw-US-x-icu", 
		"he-x-icu" => "he-x-icu", 
		"he-IL-x-icu" => "he-IL-x-icu", 
		"hi-x-icu" => "hi-x-icu", 
		"hi-IN-x-icu" => "hi-IN-x-icu", 
		"hr-x-icu" => "hr-x-icu", 
		"hr-BA-x-icu" => "hr-BA-x-icu", 
		"hr-HR-x-icu" => "hr-HR-x-icu", 
		"hsb-x-icu" => "hsb-x-icu", 
		"hsb-DE-x-icu" => "hsb-DE-x-icu", 
		"hu-x-icu" => "hu-x-icu", 
		"hu-HU-x-icu" => "hu-HU-x-icu", 
		"hy-x-icu" => "hy-x-icu", 
		"hy-AM-x-icu" => "hy-AM-x-icu", 
		"id-x-icu" => "id-x-icu", 
		"id-ID-x-icu" => "id-ID-x-icu", 
		"ig-x-icu" => "ig-x-icu", 
		"ig-NG-x-icu" => "ig-NG-x-icu", 
		"ii-x-icu" => "ii-x-icu", 
		"ii-CN-x-icu" => "ii-CN-x-icu", 
		"is-x-icu" => "is-x-icu", 
		"is-IS-x-icu" => "is-IS-x-icu", 
		"it-x-icu" => "it-x-icu", 
		"it-CH-x-icu" => "it-CH-x-icu", 
		"it-IT-x-icu" => "it-IT-x-icu", 
		"it-SM-x-icu" => "it-SM-x-icu", 
		"it-VA-x-icu" => "it-VA-x-icu", 
		"ja-x-icu" => "ja-x-icu", 
		"ja-JP-x-icu" => "ja-JP-x-icu", 
		"jgo-x-icu" => "jgo-x-icu", 
		"jgo-CM-x-icu" => "jgo-CM-x-icu", 
		"jmc-x-icu" => "jmc-x-icu", 
		"jmc-TZ-x-icu" => "jmc-TZ-x-icu", 
		"ka-x-icu" => "ka-x-icu", 
		"ka-GE-x-icu" => "ka-GE-x-icu", 
		"kab-x-icu" => "kab-x-icu", 
		"kab-DZ-x-icu" => "kab-DZ-x-icu", 
		"kam-x-icu" => "kam-x-icu", 
		"kam-KE-x-icu" => "kam-KE-x-icu", 
		"kde-x-icu" => "kde-x-icu", 
		"kde-TZ-x-icu" => "kde-TZ-x-icu", 
		"kea-x-icu" => "kea-x-icu", 
		"kea-CV-x-icu" => "kea-CV-x-icu", 
		"khq-x-icu" => "khq-x-icu", 
		"khq-ML-x-icu" => "khq-ML-x-icu", 
		"ki-x-icu" => "ki-x-icu", 
		"ki-KE-x-icu" => "ki-KE-x-icu", 
		"kk-x-icu" => "kk-x-icu", 
		"kk-KZ-x-icu" => "kk-KZ-x-icu", 
		"kkj-x-icu" => "kkj-x-icu", 
		"kkj-CM-x-icu" => "kkj-CM-x-icu", 
		"kl-x-icu" => "kl-x-icu", 
		"kl-GL-x-icu" => "kl-GL-x-icu", 
		"kln-x-icu" => "kln-x-icu", 
		"kln-KE-x-icu" => "kln-KE-x-icu", 
		"km-x-icu" => "km-x-icu", 
		"km-KH-x-icu" => "km-KH-x-icu", 
		"kn-x-icu" => "kn-x-icu", 
		"kn-IN-x-icu" => "kn-IN-x-icu", 
		"ko-x-icu" => "ko-x-icu", 
		"ko-KP-x-icu" => "ko-KP-x-icu", 
		"ko-KR-x-icu" => "ko-KR-x-icu", 
		"kok-x-icu" => "kok-x-icu", 
		"kok-IN-x-icu" => "kok-IN-x-icu", 
		"ks-x-icu" => "ks-x-icu", 
		"ks-IN-x-icu" => "ks-IN-x-icu", 
		"ksb-x-icu" => "ksb-x-icu", 
		"ksb-TZ-x-icu" => "ksb-TZ-x-icu", 
		"ksf-x-icu" => "ksf-x-icu", 
		"ksf-CM-x-icu" => "ksf-CM-x-icu", 
		"ksh-x-icu" => "ksh-x-icu", 
		"ksh-DE-x-icu" => "ksh-DE-x-icu", 
		"kw-x-icu" => "kw-x-icu", 
		"kw-GB-x-icu" => "kw-GB-x-icu", 
		"ky-x-icu" => "ky-x-icu", 
		"ky-KG-x-icu" => "ky-KG-x-icu", 
		"lag-x-icu" => "lag-x-icu", 
		"lag-TZ-x-icu" => "lag-TZ-x-icu", 
		"lb-x-icu" => "lb-x-icu", 
		"lb-LU-x-icu" => "lb-LU-x-icu", 
		"lg-x-icu" => "lg-x-icu", 
		"lg-UG-x-icu" => "lg-UG-x-icu", 
		"lkt-x-icu" => "lkt-x-icu", 
		"lkt-US-x-icu" => "lkt-US-x-icu", 
		"ln-x-icu" => "ln-x-icu", 
		"ln-AO-x-icu" => "ln-AO-x-icu", 
		"ln-CD-x-icu" => "ln-CD-x-icu", 
		"ln-CF-x-icu" => "ln-CF-x-icu", 
		"ln-CG-x-icu" => "ln-CG-x-icu", 
		"lo-x-icu" => "lo-x-icu", 
		"lo-LA-x-icu" => "lo-LA-x-icu", 
		"lrc-x-icu" => "lrc-x-icu", 
		"lrc-IQ-x-icu" => "lrc-IQ-x-icu", 
		"lrc-IR-x-icu" => "lrc-IR-x-icu", 
		"lt-x-icu" => "lt-x-icu", 
		"lt-LT-x-icu" => "lt-LT-x-icu", 
		"lu-x-icu" => "lu-x-icu", 
		"lu-CD-x-icu" => "lu-CD-x-icu", 
		"luo-x-icu" => "luo-x-icu", 
		"luo-KE-x-icu" => "luo-KE-x-icu", 
		"luy-x-icu" => "luy-x-icu", 
		"luy-KE-x-icu" => "luy-KE-x-icu", 
		"lv-x-icu" => "lv-x-icu", 
		"lv-LV-x-icu" => "lv-LV-x-icu", 
		"mas-x-icu" => "mas-x-icu", 
		"mas-KE-x-icu" => "mas-KE-x-icu", 
		"mas-TZ-x-icu" => "mas-TZ-x-icu", 
		"mer-x-icu" => "mer-x-icu", 
		"mer-KE-x-icu" => "mer-KE-x-icu", 
		"mfe-x-icu" => "mfe-x-icu", 
		"mfe-MU-x-icu" => "mfe-MU-x-icu", 
		"mg-x-icu" => "mg-x-icu", 
		"mg-MG-x-icu" => "mg-MG-x-icu", 
		"mgh-x-icu" => "mgh-x-icu", 
		"mgh-MZ-x-icu" => "mgh-MZ-x-icu", 
		"mgo-x-icu" => "mgo-x-icu", 
		"mgo-CM-x-icu" => "mgo-CM-x-icu", 
		"mk-x-icu" => "mk-x-icu", 
		"mk-MK-x-icu" => "mk-MK-x-icu", 
		"ml-x-icu" => "ml-x-icu", 
		"ml-IN-x-icu" => "ml-IN-x-icu", 
		"mn-x-icu" => "mn-x-icu", 
		"mn-MN-x-icu" => "mn-MN-x-icu", 
		"mr-x-icu" => "mr-x-icu", 
		"mr-IN-x-icu" => "mr-IN-x-icu", 
		"ms-x-icu" => "ms-x-icu", 
		"ms-BN-x-icu" => "ms-BN-x-icu", 
		"ms-MY-x-icu" => "ms-MY-x-icu", 
		"ms-SG-x-icu" => "ms-SG-x-icu", 
		"mt-x-icu" => "mt-x-icu", 
		"mt-MT-x-icu" => "mt-MT-x-icu", 
		"mua-x-icu" => "mua-x-icu", 
		"mua-CM-x-icu" => "mua-CM-x-icu", 
		"my-x-icu" => "my-x-icu", 
		"my-MM-x-icu" => "my-MM-x-icu", 
		"mzn-x-icu" => "mzn-x-icu", 
		"mzn-IR-x-icu" => "mzn-IR-x-icu", 
		"naq-x-icu" => "naq-x-icu", 
		"naq-NA-x-icu" => "naq-NA-x-icu", 
		"nb-x-icu" => "nb-x-icu", 
		"nb-NO-x-icu" => "nb-NO-x-icu", 
		"nb-SJ-x-icu" => "nb-SJ-x-icu", 
		"nd-x-icu" => "nd-x-icu", 
		"nd-ZW-x-icu" => "nd-ZW-x-icu", 
		"nds-x-icu" => "nds-x-icu", 
		"nds-DE-x-icu" => "nds-DE-x-icu", 
		"nds-NL-x-icu" => "nds-NL-x-icu", 
		"ne-x-icu" => "ne-x-icu", 
		"ne-IN-x-icu" => "ne-IN-x-icu", 
		"ne-NP-x-icu" => "ne-NP-x-icu", 
		"nl-x-icu" => "nl-x-icu", 
		"nl-AW-x-icu" => "nl-AW-x-icu", 
		"nl-BE-x-icu" => "nl-BE-x-icu", 
		"nl-BQ-x-icu" => "nl-BQ-x-icu", 
		"nl-CW-x-icu" => "nl-CW-x-icu", 
		"nl-NL-x-icu" => "nl-NL-x-icu", 
		"nl-SR-x-icu" => "nl-SR-x-icu", 
		"nl-SX-x-icu" => "nl-SX-x-icu", 
		"nmg-x-icu" => "nmg-x-icu", 
		"nmg-CM-x-icu" => "nmg-CM-x-icu", 
		"nn-x-icu" => "nn-x-icu", 
		"nn-NO-x-icu" => "nn-NO-x-icu", 
		"nnh-x-icu" => "nnh-x-icu", 
		"nnh-CM-x-icu" => "nnh-CM-x-icu", 
		"nus-x-icu" => "nus-x-icu", 
		"nus-SS-x-icu" => "nus-SS-x-icu", 
		"nyn-x-icu" => "nyn-x-icu", 
		"nyn-UG-x-icu" => "nyn-UG-x-icu", 
		"om-x-icu" => "om-x-icu", 
		"om-ET-x-icu" => "om-ET-x-icu", 
		"om-KE-x-icu" => "om-KE-x-icu", 
		"or-x-icu" => "or-x-icu", 
		"or-IN-x-icu" => "or-IN-x-icu", 
		"os-x-icu" => "os-x-icu", 
		"os-GE-x-icu" => "os-GE-x-icu", 
		"os-RU-x-icu" => "os-RU-x-icu", 
		"pa-x-icu" => "pa-x-icu", 
		"pa-Arab-x-icu" => "pa-Arab-x-icu", 
		"pa-Arab-PK-x-icu" => "pa-Arab-PK-x-icu", 
		"pa-Guru-x-icu" => "pa-Guru-x-icu", 
		"pa-Guru-IN-x-icu" => "pa-Guru-IN-x-icu", 
		"pl-x-icu" => "pl-x-icu", 
		"pl-PL-x-icu" => "pl-PL-x-icu", 
		"ps-x-icu" => "ps-x-icu", 
		"ps-AF-x-icu" => "ps-AF-x-icu", 
		"pt-x-icu" => "pt-x-icu", 
		"pt-AO-x-icu" => "pt-AO-x-icu", 
		"pt-BR-x-icu" => "pt-BR-x-icu", 
		"pt-CH-x-icu" => "pt-CH-x-icu", 
		"pt-CV-x-icu" => "pt-CV-x-icu", 
		"pt-GQ-x-icu" => "pt-GQ-x-icu", 
		"pt-GW-x-icu" => "pt-GW-x-icu", 
		"pt-LU-x-icu" => "pt-LU-x-icu", 
		"pt-MO-x-icu" => "pt-MO-x-icu", 
		"pt-MZ-x-icu" => "pt-MZ-x-icu", 
	);
	
	//see more in http://php.net/manual/en/function.pg-field-type.php and http://dev.mysql.com/doc/workbench/en/wb-migration-database-postgresql-typemapping.html and https://www.postgresql.org/docs/9.5/datatype.html
	private static $php_to_db_column_types = array(//PHP TO POSTGRES
	    	'bit' => 'bit',
		'smallserial' => array("type" => 'smallint', "null" => false, "unique" => true, "unsigned" => true, "auto_increment" => true),
		'serial' => array("type" => 'int', "null" => false, "unique" => true, "unsigned" => true, "auto_increment" => true),
		'bigserial' => array("type" => 'bigint', "null" => false, "unique" => true, "unsigned" => true, "auto_increment" => true),
		'tinyint' => 'smallint',
		'smallint' => 'smallint',
		'int' => 'int',
		'bigint' => 'bigint',
		'decimal' => 'decimal',
		'money' => 'decimal(19,2)',
		'coordinate' => 'decimal(18,15)',
		'double' => 'double precision',
		'float' => 'real',

		'date' => 'date',
		'datetime' => 'timestamp',
		'timestamp' => 'timestamp',
		'time' => 'time',
		
		'char' => 'char',
		'varchar' => 'varchar',
		'text' => 'text',
		'mediumtext' => 'text',
		'longtext' => 'text',
		'blob' => 'bytea',
		'longblob' => 'bytea',
		
		'varchar(36)' => 'uuid',
		'varchar(44)' => 'cidr',
		'varchar(43)' => 'inet',
		'varchar(17)' => 'macaddr',
		
		'boolean' => 'boolean',
	);
	
	private static $db_to_php_column_types = array(//POSTGRES TO PHP
		'bit' => 'bit',
		'smallserial' => 'smallserial',
		'serial' => 'serial',
		'bigserial' => 'bigserial',
		'smallint' => 'smallint',
		'integer' => 'int',
		'int' => 'int',
		'bigint' => 'bigint',
		'int4' => 'int',
		'int8' => 'int',
		'decimal(18,15)' => 'coordinate',
		'decimal' => 'decimal',
		'numeric' => 'decimal',
		'double precision' => 'double',
		'real' => 'float',
		'money' => 'money',
		
		'date' => 'date',
		'interval' => 'time',
		'time' => 'time',
		'time without time zone' => 'time',
		'time with time zone' => 'timestamp',
		'timestamp' => 'timestamp',
		'timestamp without time zone' => 'timestamp',
		'timestamp with time zone' => 'timestamp',
		
		'char' => 'char',
		'character' => 'char',
		'text' => 'text',
		'varchar' => 'varchar',
		
		'cidr' => 'varchar(44)',
		'circle' => 'varchar',
		'daterange' => 'varchar',
		'inet' => 'varchar(43)',
		'int4range' => 'varchar',
		'int8range' => 'varchar',
		'json' => 'longtext',
		'lseg' => 'varchar',
		'macaddr' => 'varchar(17)',
		'numrange' => 'varchar',
		'path' => 'varchar',
		'point' => 'varchar',
		'polygon' => 'varchar',
		'bytea' => 'longblob',
		'box' => 'varchar',
		'tsquery' => 'longtext',
		'tsrange' => 'varchar',
		'tstzrange' => 'varchar',
		'tsvector' => 'longtext',
		'uuid' => 'varchar(36)',
		'bit varying' => 'varchar',
		'character varying' => 'varchar',
		'xml' => 'longtext',
		
		'boolean' => 'boolean',
	);
	
	private static $db_column_types = array( //POSTGRES SERVER TYPES
		'bit' => 'Bit',
		'smallserial' => 'Small Serial',
		'serial' => 'Serial',
		'bigserial' => 'Big Serial',
		'smallint' => 'Small Int',
		'integer' => 'Int',
		'int' => 'Int',
		'bigint' => 'Big Int',
		'int4' => 'Int 4',
		'int8' => 'Int 8',
		'decimal' => 'Decimal',
		'numeric' => 'Numeric',
		'double precision' => 'Double Precision',
		'real' => 'Real',
		'money' => 'Money',
		
		'date' => 'Date',
		'interval' => 'Interval',
		'time' => 'Time',
		'time without time zone' => 'Time without time zone',
		'time with time zone' => 'Time with time zone',
		'timestamp' => 'Timestamp',
		'timestamp without time zone' => 'Timestamp without time zone',
		'timestamp with time zone' => 'Timestamp with time zone',
		
		'char' => 'Char',
		'character' => 'Character',
		'text' => 'Text',
		'varchar' => 'Varchar',
		
		//other types
		'cidr' => 'Cidr',
		'circle' => 'Circle',
		'daterange' => 'Date Range',
		'inet' => 'Inet',
		'int4range' => 'Int 4 Range',
		'int8range' => 'Int 8 Range',
		'json' => 'Json',
		'lseg' => 'Lseg',
		'macaddr' => 'Macaddr',
		'numrange' => 'Num Range',
		'path' => 'Path',
		'point' => 'Point',
		'polygon' => 'Polygon',
		'bytea' => 'Bytea',
		'box' => 'Bbox',
		'tsquery' => ' TS Query',
		'tsrange' => 'TS Range',
		'tstzrange' => 'TS Tz Range',
		'tsvector' => 'TS Vector',
		'uuid' => 'Uuid',
		'bit varying' => 'Bit Varying',
		'character varying' => 'Character Varying',
		'xml' => 'Xml',
		
		'boolean' => 'Boolean',
	);
	
	private static $db_column_simple_types = array( //POSTGRES SERVER TYPES
		'simple_auto_primary_key' => array("type" => "bigint", "label" => "Automatic Primary Key", "length" => 20, "null" => false, "primary_key" => true, "auto_increment" => true, "unsigned" => true, "name" => "id"),
		'simple_manual_primary_key' => array("type" => "varchar", "label" => "Manual Primary Key", "length" => 255, "null" => false, "primary_key" => true, "name" => "id"),
		'simple_fk_primary_key' => array("type" => "bigint", "label" => "Automatic Primary Key From Another Table", "length" => 20, "null" => false, "primary_key" => true, "auto_increment" => false, "unsigned" => true, "name" => "id"),
		'simple_fk' => array("type" => array("bigint", "int"), "label" => "Foreign Key From Another Table", "length" => "20", "null" => true, "primary_key" => false, "auto_increment" => false, "unsigned" => true, "name" => "id"),
		'simple_current_date' => array("type" => "date", "label" => "Current Date (yyyy-mm-dd)", "default" => "CURRENT_DATE"),
		'simple_date' => array("type" => "date", "label" => "Date (yyyy-mm-dd)"),
		'simple_current_date_time' => array("type" => "datetime", "label" => "Current Date Time (yyyy-mm-dd hh:mm:ss)", "default" => "CURRENT_TIMESTAMP"),
		'simple_date_time' => array("type" => "datetime", "label" => "Date Time (yyyy-mm-dd hh:mm:ss)", "name" => array(
			"date", "data", "fecha"
		)),
		'simple_current_time' => array("type" => "time", "label" => "Current Time (hh:mm:ss)", "default" => "CURRENT_TIME"),
		'simple_time' => array("type" => "time", "label" => "Time (hh:mm:ss)", "name" => array(
			"time", "tempo", "tiempo"
		)),
		'simple_2_digits' => array("type" => array("tinyint", "smallint", "int"), "label" => "Hour, Minute or Seconds (2 digits)", "length" => 2, "name" => array(
			"hour", "hora", "heure", 
			"minute", "minuto", "minute", 
			"second", "segundo", "secondes"
		)),
		'simple_email' => array("type" => "varchar", "label" => "Email", "length" => 320, "name" => array(
			"email", "e_email"
		)),  //email max length according with RFC 5321 and RFC 5322. "name" is a different property that will check if value is in the attribute name (this is, contains searching string).
		'simple_address' => array("type" => "varchar", "label" => "Address", "length" => 300, "name" => array(
			"address", "endereco", "endereço", "morada", "habitacao", "habitação", "direccion", "dirección", "alojamiento", "adresse", "logement"
		)),
		'simple_numeric_zip_code' => array("type" => "int", "label" => "Numeric Zip Code", "length" => 4, "name" => array(
			"zip", "code", "codigo", "código", "postal"
		)),
		'simple_alpha_numeric_zip_code' => array("type" => "int", "label" => "Alpha-Numeric Zip Code", "length" => 10, "name" => array(
			"zip", "code", "codigo", "código", "postal"
		)),
		'simple_location' => array("type" => "varchar", "label" => "Location", "length" => 50, "name" => array(
			"location", "localizacao", "localização", "ubicacion", "ubicación", "localizacion", "localización", "emplacement", "localisation",
			"zone", "zona", "lugar", "local", "lugar", "sitio", "sítio", "zone", "lieu",
			"village", "vila", "aldea", "ville", 
			"city", "cidade", "ciudad", 
			"state", "estado", "État",
			"region", "regiao", "região", "region", "región", "région",
			"country", "pais", "país", "pays"
		)),
		'simple_phone' => array("type" => "varchar", "label" => "Phone", "length" => 20, "name" => array(
			"phone", "fone", "fono",
			"contact", "contacto", "contato"
		)),
		'simple_username' => array("type" => "varchar", "label" => "Username", "length" => 320, "name" => array(
			"username", "usuario", "usuário", "utilizador", "utilisateur"
		)), //email max length according with RFC 5321 and RFC 5322
		'simple_password' => array("type" => "varchar", "label" => "Password", "length" => 255, "name" => array(
			"password", "chave", "contrasena", "contraseña", "passe"
		)),
		'simple_type' => array("type" => "varchar", "label" => "Long Name", "length" => 100, "name" => array(
			"type", "tipo", "taper"
		)),
		'simple_category' => array("type" => "varchar", "label" => "Category", "length" => 150, "name" => array(
			"category", "categoria", "categoría", "categorie", "catégorie"
		)),
		'simple_summary' => array("type" => "varchar", "label" => "Summary", "length" => 1000, "name" => array(
			"summary", "sumario", "sumário", "resumen", "resume", "résumé", "sommaire"
		)),
		'simple_article' => array("type" => "varchar", "label" => "Article", "length" => 50000, "name" => array(
			"article", "artigo", "articulo", "artículo"
		)),
		'simple_comment' => array("type" => "varchar", "label" => "Comment", "length" => 2000, "name" => array(
			"comment", "comentario", "comentário", "commentaire"
		)),
		'simple_svg' => array("type" => "varchar", "label" => "SVG", "length" => 60000, "name" => "svg"),
		'simple_path' => array("type" => "varchar", "label" => "Path", "length" => 4096, "name" => array(
			"path", "rua", "caminho", "camino", "route", "chemin"
		)),
		'simple_single_name' => array("type" => "varchar", "label" => "Single Name", "length" => 30),
		'simple_short_name' => array("type" => "varchar", "label" => "Short Name", "length" => 50),
		'simple_long_name' => array("type" => "varchar", "label" => "Long Name", "length" => 200),
		'simple_name' => array("type" => "varchar", "label" => "Name", "name" => array(
			"name", "nome", "nombre", "nom",
			"title", "titulo", "título", "titre",
			"label", "etiqueta", "etiquette", "étiquette"
		)),
		'simple_description' => array("type" => "text", "label" => "Description", "name" => array(
			"description", "descricao", "descrição", "descripcion", "descripción",
			"note", "nota"
		)),
		'simple_boolean' => array("type" => array("bit", "smallint"), "label" => "Boolean/Bit", "length" => 1, "name" => array(
			"status", "estado", "condicao", "condição", "statut",
			"enable", "allow", "habilitar", "permitir", "habiliter",
			"disable",
			"active", "ativar", "activar", "activer", 
			"inactive", "desativar", "desactivar", "desactiver", "désactiver", 
			"mandatory", "obrigatori", "obrigatóri", "obligatori", "obligatoire",
			"optional", "opcional", "facultativo", "facultative",
			"closed", "fechado", "fechada", "cerrado", "cerrada", "fermé",
			"open", "aberto", "aberta", "abierto", "abierta", "ouvrir"
		)),
		'simple_order' => array("type" => array("tinyint", "smallint", "int"), "label" => "Order", "length" => 5, "name" => array(
			"order", "ordem", "orden", "ordre"
		)),
		'simple_rating' => array("type" => array("tinyint", "smallint", "int"), "label" => "Rating", "length" => 2, "name" => array(
			"rating", "evaluation", "classificacao", "classificação", "avaliacao", "avaliação", "clasificacion", "clasificación", "valuacion", "valuación", "notation", "évaluation"
		)),
		'simple_age' => array("type" => array("tinyint", "smallint", "int"), "label" => "Age", "length" => 3, "name" => array(
			"age", "idade", "edad", "âge"
		)),
		'simple_height' => array("type" => array("decimal", "double precision"), "label" => "Height", "length" => "4,1", "name" => array(
			"height", "altura", "hauteur"
		)),
		'simple_weight' => array("type" => array("decimal", "double precision"), "label" => "Weight", "length" => "5,2", "name" => array(
			"weight", "peso", "poids"
		)),
		'simple_big_weight' => array("type" => array("decimal", "double precision"), "label" => "Big Weight", "length" => "10,2"),
		'simple_currency' => array("type" => array("decimal", "double precision"), "label" => "Currency", "length" => "37,8", "name" => array(
			"currency", "price", "moeda", "preco", "preço", "divisa", "moneda", "precio", "devise", "monnaie", "prix"
		)),
		'simple_size' => array("type" => "bigint", "label" => "Size", "name" => array(
			"size", "tamanho", "tamaño", "taille"
		)),
		'simple_binary' => array("type" => "bytea", "label" => "Binary/File", "name" => array(
			"attachment", "anexo", "adjunto", "jointe", "attachement",
			"image", "imagem", "imagen",
			"video", "movie", "vídeo", "filme", "pelicula", "película", "vidéo",
			"document", "documento",
			"file", "ficheiro", "archivo", "dossier", "deposer", "déposer"
		)),
		'simple_int' => array("type" => "int", "label" => "Integer", "name" => "int"),
		'simple_big_int' => array("type" => "bigint", "label" => "Big Integer"),
		'simple_decimal_2_digits' => array("type" => array("decimal", "double precision"), "label" => "Decimal 2 digits", "length" => "10,8"),
		'simple_coordinate' => array("type" => array("decimal", "double", "float"), "label" => "Coordinate", "length" => "12,8", "name" => array(
			"coordinate", "coordenada", "coordonne", "coordonné",
			"latitude", "latitud",
			"longitude", "longitud"
		)),
		'simple_decimal' => array("type" => array("decimal", "double precision"), "label" => "Decimal", "name" => array(
			"decimal", "décimale"
		)),
		'simple_numeric' => array("type" => "numeric", "label" => "Number", "name" => array(
			"number", "numero", "número", "numéro"
		)),
	);
	
	private static $db_column_default_values_by_type = array(
		'bit' => '0',
		'smallserial' => '0',
		'serial' => '0',
		'bigserial' => '0',
		'smallint' => '0',
		'integer' => '0',
		'int' => '0',
		'bigint' => '0',
		'int4' => '0',
		'int8' => '0',
		'decimal' => '0',
		'numeric' => '0',
		'double precision' => '0',
		'real' => '0',
		'money' => '0',
		
		'date' => '0000-00-00',
		'interval' => '0',
		'time' => '00:00:00',
		'time without time zone' => '00:00:00',
		'time with time zone' => '00:00:00',
		'timestamp' => '0000-00-00 00:00:00',
		'timestamp without time zone' => '0000-00-00 00:00:00',
		'timestamp with time zone' => '0000-00-00 00:00:00',
		
		'char' => '',
		'character' => '',
		'varchar' => '',
		'text' => '',
		
		'cidr' => '',
		'circle' => '',
		'daterange' => '',
		'inet' => '',
		'int4range' => '',
		'int8range' => '',
		'json' => '',
		'lseg' => '',
		'macaddr' => '',
		'numrange' => '',
		'path' => '',
		'point' => '',
		'polygon' => '',
		'bytea' => '',
		'box' => '',
		'tsquery' => '',
		'tsrange' => '',
		'tstzrange' => '',
		'tsvector' => '',
		'uuid' => '',
		'bit varying' => '',
		'character varying' => '',
		'xml' => '',
		
		'boolean' => 'false',//but it could be "yes" or "no" too.
	);
	
	//More in https://www.postgresql.org/docs/9.5/datatype.html
	private static $db_column_types_ignored_props = array(
		//if numeric the length is not allowed
		'bit' => array("unsigned", "auto_increment", "charset", "collation"),
		'smallserial' => array("length", "charset", "collation"),
		'serial' => array("length", "charset", "collation"),
		'bigserial' => array("length", "charset", "collation"),
		'smallint' => array("length", "charset", "collation"),
		'integer' => array("length", "charset", "collation"),
		'int' => array("length", "charset", "collation"),
		'bigint' => array("length", "charset", "collation"),
		'int4' => array("length", "charset", "collation"),
		'int8' => array("length", "charset", "collation"),
		'decimal' => array("charset", "collation"),
		'numeric' => array("charset", "collation"),
		'double precision' => array("length", "charset", "collation"),
		'real' => array("length", "charset", "collation"),
		'money' => array("length", "charset", "collation"),
		
		'date' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'interval' => array("unsigned", "auto_increment", "charset", "collation"),
		'time' => array("unsigned", "auto_increment", "charset", "collation"),
		'time without time zone' => array("unsigned", "auto_increment", "charset", "collation"),
		'time with time zone' => array("unsigned", "auto_increment", "charset", "collation"),
		'timestamp' => array("unsigned", "auto_increment", "charset", "collation"),
		'timestamp without time zone' => array("unsigned", "auto_increment", "charset", "collation"),
		'timestamp with time zone' => array("unsigned", "auto_increment", "charset", "collation"),
		
		'char' => array("unsigned", "auto_increment", "charset"),
		'character' => array("unsigned", "auto_increment", "charset"),
		'varchar' => array("unsigned", "auto_increment", "charset"),
		'text' => array("length", "unsigned", "auto_increment", "charset"),
		
		'cidr' => array("length", "unsigned", "auto_increment", "charset"),
		'circle' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'daterange' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'inet' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'int4range' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'int8range' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'json' => array("length", "unsigned", "auto_increment", "charset"),
		'lseg' => array("length", "unsigned", "auto_increment", "charset"),
		'macaddr' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'numrange' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'path' => array("length", "unsigned", "auto_increment", "charset"),
		'point' => array("length", "unsigned", "auto_increment", "charset"),
		'polygon' => array("length", "unsigned", "auto_increment", "charset"),
		'bytea' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'box' => array("length", "unsigned", "auto_increment", "charset"),
		'tsquery' => array("length", "unsigned", "auto_increment", "charset"),
		'tsrange' => array("length", "unsigned", "auto_increment", "charset"),
		'tstzrange' => array("length", "unsigned", "auto_increment", "charset"),
		'tsvector' => array("length", "unsigned", "auto_increment", "charset"),
		'uuid' => array("length", "unsigned", "auto_increment", "charset", "collation"),
		'bit varying' => array("unsigned", "auto_increment", "charset", "collation"),
		'character varying' => array("unsigned", "auto_increment", "charset"),
		'xml' => array("length", "unsigned", "auto_increment", "charset"),
		
		'boolean' => array("length", "unsigned", "auto_increment", "charset", "collation"),
	);
	
	private static $db_column_numeric_types = array('bit', 'smallserial', 'serial', 'bigserial', 'smallint', 'integer', 'int', 'bigint', 'int4', 'int8', 'decimal', 'numeric', 'double precision', 'real', 'money');
	
	private static $db_column_date_types = array('date', 'interval', 'time without time zone', 'time with time zone', 'timestamp','timestamp without time zone', 'timestamp with time zone');
	
	private static $db_column_text_types = array('char', 'character', 'varchar', 'text');
	
	private static $db_column_blob_types = array('bytea', 'circle', 'lseg', 'path', 'point', 'polygon', 'tsquery', 'tsrange', 'tstzrange', 'tsvector', 'bit varying'); //Do not add text, varchar, bit, xml, json here
	
	private static $db_column_boolean_types = array('boolean');
	
	private static $db_column_mandatory_length_types = array(); //https://www.postgresql.org/docs/current/datatype.html
	
	private static $db_column_auto_increment_types = array('smallserial', 'serial', 'bigserial');
	
	private static $db_boolean_type_available_values = array("t" => "true", "f" => "false");
	
	private static $db_current_timestamp_available_values = array("CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP()");
	
	private static $attribute_value_reserved_words = array("CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "DEFAULT", "NULL", "TRUE", "FALSE");
	
	private static $reserved_words = array("*", "ABORT", "ABS", "ABSOLUTE", "ACCESS", "ACTION", "ADA", "ADD", "ADMIN", "AFTER", "AGGREGATE", "ALIAS", "ALL", "ALLOCATE", "ALTER", "ANALYSE", "ANALYZE", "AND", "ANY", "ARE", "ARRAY", "AS", "ASC", "ASENSITIVE", "ASSERTION", "ASSIGNMENT", "ASYMMETRIC", "AT", "ATOMIC", "AUTHORIZATION", "AVG", "BACKWARD", "BEFORE", "BEGIN", "BETWEEN", "BIGINT", "BINARY", "BIT", "BITVAR", "BIT_LENGTH", "BLOB", "BOOLEAN", "BOTH", "BREADTH", "BY", "C", "CACHE", "CALL", "CALLED", "CARDINALITY", "CASCADE", "CASCADED", "CASE", "CAST", "CATALOG", "CATALOG_NAME", "CHAIN", "CHAR", "CHARACTER", "CHARACTERISTICS", "CHARACTER_LENGTH", "CHARACTER_SET_CATALOG", "CHARACTER_SET_NAME", "CHARACTER_SET_SCHEMA", "CHAR_LENGTH", "CHECK", "CHECKED", "CHECKPOINT", "CLASS", "CLASS_ORIGIN", "CLOB", "CLOSE", "CLUSTER", "COALESCE", "COBOL", "COLLATE", "COLLATION", "COLLATION_CATALOG", "COLLATION_NAME", "COLLATION_SCHEMA", "COLUMN", "COLUMN_NAME", "COMMAND_FUNCTION", "COMMAND_FUNCTION_CODE", "COMMENT", "COMMIT", "COMMITTED", "COMPLETION", "CONDITION_NUMBER", "CONNECT", "CONNECTION", "CONNECTION_NAME", "CONSTRAINT", "CONSTRAINTS", "CONSTRAINT_CATALOG", "CONSTRAINT_NAME", "CONSTRAINT_SCHEMA", "CONSTRUCTOR", "CONTAINS", "CONTINUE", "CONVERSION", "CONVERT", "COPY", "CORRESPONDING", "COUNT", "CREATE", "CREATEDB", "CREATEUSER", "CROSS", "CUBE", "CURRENT", "CURRENT_DATE", "CURRENT_PATH", 
	"CURRENT_ROLE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR", "CURSOR_NAME", "CYCLE", "DATA", "DATABASE", "DATE", "DATETIME_INTERVAL_CODE", "DATETIME_INTERVAL_PRECISION", "DAY", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DEFERRABLE", "DEFERRED", "DEFINED", "DEFINER", "DELETE", "DELIMITER", "DELIMITERS", "DEPTH", "DEREF", "DESC", "DESCRIBE", "DESCRIPTOR", "DESTROY", "DESTRUCTOR", "DETERMINISTIC", "DIAGNOSTICS", "DICTIONARY", "DISCONNECT", "DISPATCH", "DISTINCT", "DO", "DOMAIN", "DOUBLE", "DROP", "DYNAMIC", "DYNAMIC_FUNCTION", "DYNAMIC_FUNCTION_CODE", "EACH", "ELSE", "ENCODING", "ENCRYPTED", "END", "END-EXEC", "EQUALS", "ESCAPE", "EVERY", "EXCEPT", "EXCEPTION", "EXCLUSIVE", "EXEC", "EXECUTE", "EXISTING", "EXISTS", "EXPLAIN", "EXTERNAL", "EXTRACT", "FALSE", "FETCH", "FINAL", "FIRST", "FLOAT", "FOR", "FORCE", "FOREIGN", "FORTRAN", "FORWARD", "FOUND", "FREE", "FREEZE", "FROM", "FULL", "FUNCTION", "G", "GENERAL", "GENERATED", "GET", "GLOBAL", "GO", "GOTO", "GRANT", "GRANTED", "GROUP", "GROUPING", "HANDLER", "HAVING", "HIERARCHY", "HOLD", "HOST", "HOUR", "IDENTITY", 
	"IGNORE", "ILIKE", "IMMEDIATE", "IMMUTABLE", "IMPLEMENTATION", "IMPLICIT", "IN", "INCREMENT", "INDEX", "INDICATOR", "INFIX", "INHERITS", "INITIALIZE", "INITIALLY", "INNER", "INOUT", "INPUT", "INSENSITIVE", "INSERT", "INSTANCE", "INSTANTIABLE", "INSTEAD", "INT", "INTEGER", "INTERSECT", "INTERVAL", "INTO", "INVOKER", "IS", "ISNULL", "ISOLATION", "ITERATE", "JOIN", "K", "KEY", "KEY_MEMBER", "KEY_TYPE", "LANCOMPILER", "LANGUAGE", "LARGE", "LAST", "LATERAL", "LEADING", "LEFT", "LENGTH", "LESS", "LEVEL", "LIKE", "LIMIT", "LISTEN", "LOAD", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP", "LOCATION", "LOCATOR", "LOCK", "LOWER", "M", "MAP", "MATCH", "MAX", "MAXVALUE", "MESSAGE_LENGTH", "MESSAGE_OCTET_LENGTH", "MESSAGE_TEXT", "METHOD", "MIN", "MINUTE", "MINVALUE", "MOD", "MODE", "MODIFIES", "MODIFY", "MODULE", "MONTH", "MORE", "MOVE", "MUMPS", 
	"NAME", "NAMES", "NATIONAL", "NATURAL", "NCHAR", "NCLOB", "NEW", "NEXT", "NO", "NOCREATEDB", "NOCREATEUSER", "NONE", "NOT", "NOTHING", "NOTIFY", "NOTNULL", "NULL", "NULLABLE", "NULLIF", "NUMBER", "NUMERIC", "OBJECT", "OCTET_LENGTH", "OF", "OFF", "OFFSET", "OIDS", "OLD", "ON", "ONLY", "OPEN", "OPERATION", "OPERATOR", "OPTION", "OPTIONS", "OR", "ORDER", "ORDINALITY", "OUT", "OUTER", "OUTPUT", "OVERLAPS", "OVERLAY", "OVERRIDING", "OWNER", "PAD", "PARAMETER", "PARAMETERS", "PARAMETER_MODE", "PARAMETER_NAME", "PARAMETER_ORDINAL_POSITION", "PARAMETER_SPECIFIC_CATALOG", "PARAMETER_SPECIFIC_NAME", "PARAMETER_SPECIFIC_SCHEMA", "PARTIAL", "PASCAL", "PASSWORD", "PATH", "PENDANT", "PLACING", "PLI", "POSITION", "POSTFIX", "PRECISION", "PREFIX", "PREORDER", "PREPARE", "PRESERVE", "PRIMARY", "PRIOR", "PRIVILEGES", "PROCEDURAL", "PROCEDURE", "PUBLIC", "READ", "READS", "REAL", "RECHECK", "RECURSIVE", "REF", "REFERENCES", "REFERENCING", "REINDEX", "RELATIVE", "RENAME", "REPEATABLE", "REPLACE", "RESET", "RESTRICT", "RESULT", "RETURN", "RETURNED_LENGTH", "RETURNED_OCTET_LENGTH", "RETURNED_SQLSTATE", "RETURNS", "REVOKE", "RIGHT", "ROLE", "ROLLBACK", "ROLLUP", "ROUTINE", "ROUTINE_CATALOG", "ROUTINE_NAME", "ROUTINE_SCHEMA", "ROW", "ROWS", "ROW_COUNT", "RULE", "SAVEPOINT", "SCALE", "SCHEMA", "SCHEMA_NAME", "SCOPE", "SCROLL", "SEARCH", "SECOND", "SECTION", "SECURITY", "SELECT", "SELF", 
	"SENSITIVE", "SEQUENCE", "SERIALIZABLE", "SERVER_NAME", "SESSION", "SESSION_USER", "SET", "SETOF", "SETS", "SHARE", "SHOW", "SIMILAR", "SIMPLE", "SIZE", "SMALLINT", "SOME", "SOURCE", "SPACE", "SPECIFIC", "SPECIFICTYPE", "SPECIFIC_NAME", "SQL", "SQLCODE", "SQLERROR", "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "STABLE", "START", "STATE", "STATEMENT", "STATIC", "STATISTICS", "STDIN", "STDOUT", "STORAGE", "STRICT", "STRUCTURE", "STYLE", "SUBCLASS_ORIGIN", "SUBLIST", "SUBSTRING", "SUM", "SYMMETRIC", "SYSID", "SYSTEM", "SYSTEM_USER", "TABLE", "TABLE_NAME", "TEMP", "TEMPLATE", "TEMPORARY", "TERMINATE", "THAN", "THEN", "TIME", "TIMESTAMP", "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TO", "TOAST", "TRAILING", "TRANSACTION", "TRANSACTIONS_COMMITTED", "TRANSACTIONS_ROLLED_BACK", "TRANSACTION_ACTIVE", "TRANSFORM", "TRANSFORMS", "TRANSLATE", 
	"TRANSLATION", "TREAT", "TRIGGER", "TRIGGER_CATALOG", "TRIGGER_NAME", "TRIGGER_SCHEMA", "TRIM", "TRUE", "TRUNCATE", "TRUSTED", "TYPE", "UNCOMMITTED", "UNDER", "UNENCRYPTED", "UNION", "UNIQUE", "UNKNOWN", "UNLISTEN", "UNNAMED", "UNNEST", "UNTIL", "UPDATE", "UPPER", "USAGE", "USER", "USER_DEFINED_TYPE_CATALOG", "USER_DEFINED_TYPE_NAME", "USER_DEFINED_TYPE_SCHEMA", "USING", "VACUUM", "VALID", "VALIDATOR", "VALUE", "VALUES", "VARCHAR", "VARIABLE", "VARYING", "VERBOSE", "VERSION", "VIEW", "VOLATILE", "WHEN", "WHENEVER", "WHERE", "WITH", "WITHOUT", "WORK", "WRITE", "YEAR", "ZONE",
	"NEXTVAL"
);
	
}
?>
